WIP - Validaciones en el modelo Player y algunas pruebas unitarias
Amigos-Informaticos/Loteria pull request #23
Opened 2020-11-15 08:23 UTC by VeggieCode

2020-11-15 18:24 UTC, W3Edd commented
Nadie va a mergearlo hasta que le quites el WIP.

2020-11-15 18:27 UTC, W3Edd requested changes

2020-11-15 18:27 UTC, W3Edd commented on Assets/Logic/Model/Player.cs
> +
CodeFactor dice que no debe haber lineas vacias despues de llaves que cierran.

2020-11-17 06:19 UTC, W3Edd approved these changes

2020-11-17 06:19 UTC, VeggieCode commented on Assets/Logic/Model/Player.cs
> +
Ya

2020-11-17 06:19 UTC, merged